version: "3.8"

services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      FLASK_ENV: development
